config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :welcome
  resources :trainers
  resources :owners
  resources :dog_breeds
  resources :breeds
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :dogs

  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
    #@dogs = Dog.all
    @owner = Owner.find(params[:id])
    @dogs = Dog.select{|dog| dog.owner_id == @owner.id}
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_alt_form.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
 <head>
   <meta charset="utf-8">
   <title></title>
 </head>
 <body>
   <div class="container">

   <p id="notice"><%= notice %></p>
<h1><%= "Hello, #{@owner.name}!" %></h1>
<br>
<br>

<h3><%= "You haven't adopted any pups yet - Please visit our pups page!" %></h3>

<br>
<br>

<h4><%= link_to 'Edit Name', edit_owner_path(@owner) %> | <%= link_to 'Back', owners_path %></h4>

app/views/owners/_form.html.erb
<%= form_with(model: owner, local: true) do |form| %>
  <% if owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/owners/_show_form.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
 <head>
   <meta charset="utf-8">
   <title></title>
 </head>
 <body>
   <div class="container">

   <p id="notice"><%= notice %></p>
<h1><%= "Hello, #{@owner.name}!" %></h1>
<h3><%= "These are the dogs you've adopted." %></h3>

<% @dogs.each do |dog| %>
  <div class="row">
  <div class="col-4">
    <ul class ="list-group">
      <li class="list-group-item"><%= link_to dog.name, dog %></li>
    </ul>
  </div>
  </div>
<% end %>


<h4><%= link_to 'Edit Name', edit_owner_path(@owner) %> | <%= link_to 'Back', owners_path %></h4>

app/views/owners/edit.html.erb
<h1>Change Your Name!</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="container">

<p id="notice"><%= notice %></p>

<h1>Owners</h1>



  <% @owners.each do |owner| %>
    <div class="row">
    <div class="col-6">
      <ul class ="list-group">
      <br>
      <li class="list-group-item">Name: <%= owner.name %></li>
      <li class="list-group-item"><%= link_to 'Profile Page', owner %></li>
      </ul>
    </div>
    </div>
  <% end %>


<br>

<h4><%= link_to 'New Owner', new_owner_path %> | <%= link_to 'Back', welcome_path(:index) %></h4>

app/views/owners/new.html.erb
<h1>Future Owner</h1>

<h4><%= render 'form', owner: @owner %></h4>

<h4><%= link_to 'Back', welcome_path(:index) %></h4>

app/views/owners/show.html.erb
<% if @dogs.length >=  1 %>
  <%= render 'show_form', owner: @owner %>
<% else %>
  <%= render 'alt_form', owner: @owner %>
<% end %>