config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :welcome
  resources :trainers
  resources :owners
  resources :dog_breeds
  resources :breeds
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :owner, optional: true
  belongs_to :trainer, optional: true
  has_many :dog_breeds
  has_many :breeds, through: :dog_breeds


    def self.dog_average_age
      Dog.average(:age)
    end

    def self.dog_total
      Dog.count
    end

    # def self.dog_count_per_breed
    #   Dog.count(:breed_id)
    # end

  #   def self.most_common_breed
  #     breed_counter = 0
  #     @dogs.each do |dog|
  #       if
  #
  #     breed_counter += 1
  #   end
  # end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json

  def index

    @dogs = Dog.all.select{ |dog| dog.owner_id == nil}
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @dogbreeds = DogBreed.select{ |dogbreed| dogbreed.dog_id == @dog.id }
    @breeds = @dogbreeds.map do |dogbreed|
      Breed.find(dogbreed.breed_id)
    end

  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :age, :size, :kids_compatible, :pets_compatible, :image_url, :fixed, :vaccinated, :bio, :trainer_id, :owner_id)
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_with(model: dog, local: true) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :owner_id %>
    <%= form.collection_select :owner_id, Owner.all, :id, :name  %>
  </div>

<br>

<h4>Would you like to sign up your dog for training?</h4>
<h5>Please select one of our qualified trainers.</h5>
<%= link_to 'View Trainers', trainers_path %>
  <div class="field">
    <%= form.label :trainer_id %>
    <%= form.collection_select :trainer_id, Trainer.all, :id, :name  %>
  </div>



  <div class="actions">
    <%= form.submit "Submit"%>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Congratulations!</h1>

<h3>Please select your name.</h3>

<h4><%= render 'form', dog: @dog %></h4>

<br>
<br>

<h4><%= link_to 'View Dog', @dog %> | <%= link_to 'Back', dogs_path %></h4>

app/views/dogs/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
 <head>
   <meta charset="utf-8">
   <title></title>
 </head>
 <body>
   <div class="container">

   <p id="notice"><%= notice %></p>

   <h1>Pups</h1>


    <% @dogs.each do |dog| %>
        <div class="row">
          <div class="col-6">
            <ul class ="list-group">
              <br>
              <li class="list-group-item">Name: <%= link_to dog.name, dog_path(dog.id) %></li>
              <br>
              <li class="list-group-item">Age: <%= dog.age %></li>
              <li class="list-group-item">Size: <%= dog.size %></li>
              <li class="list-group-item">Bio: <%= dog.bio %></li>
              <li class="list-group-item"><%= link_to 'Adopt', edit_dog_path(dog) %></li>

            </ul>
          </div>
          <div class="col-5">
            <li class="list-group-item img_cont"> <%= image_tag dog.image_url, :class => "img-fluid", :style => 'height: 350px'%></li>
          </div>
        </div>
        <% end %>


   </div>
 </body>
</html>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="col-6">
<ul class ="list-group">
  <li class="list-group-item">Name: <%= @dog.name %></li>
  <li class="list-group-item"> Breed:
  <% @breeds.each do |breed| %>
  <%= link_to breed.name, breed_path(breed) %>
  <% end %>
  </li>
  <li class="list-group-item">Age: <%= @dog.age %></li>
  <li class="list-group-item">Size: <%= @dog.size %></li>
  <li class="list-group-item">Bio: <%= @dog.bio %></li>
  <% kid_comp = @dog.kids_compatible.to_s %>
  <li class="list-group-item">Kid Friendly? <%= kid_comp == "true"? "Yes" : "No" %>
  <% pets_comp = @dog.pets_compatible.to_s %>
  <li class="list-group-item">Pet Friendly? <%= pets_comp == "true"? "Yes" : "No" %>
  <% fix = @dog.fixed.to_s %>
  <li class="list-group-item">Fixed? <%= fix == "true"? "Yes" : "No" %>
  <% vacc = @dog.vaccinated.to_s %>
  <li class="list-group-item">Vaccinated? <%= vacc == "true"? "Yes" : "No" %>
  <li class="list-group-item"><%= link_to 'Adopt', edit_dog_path(@dog) %></li>
  </ul>
</div>
<div class="col-5">
<li class="list-group-item"> <%= image_tag @dog.image_url, :class => "img-fluid" %></li>
</div>
</div>