config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :welcome
  resources :trainers
  resources :owners
  resources :dog_breeds
  resources :breeds
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :dogs
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
    @trainer = Trainer.find(params[:id])
    @dogs = Dog.select{|dog| dog.trainer_id == @trainer.id}
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:name, :bio, :availble_on_weekends)
    end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/_form.html.erb
<%= form_with(model: trainer, local: true) do |form| %>
  <% if trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.collection_select :owner_id, Owner.all, :id, :name  %>
  </div>

  <div class="actions">
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Sign Up Your Dog For Training!</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="container">

<p id="notice"><%= notice %></p>

<h1>Trainers</h1>


  <% @trainers.each do |trainer| %>
    <div class="row">
    <div class="col-6">
      <ul class ="list-group">
      <br>
      <li class="list-group-item">Name: <%= link_to trainer.name, trainer_path(trainer.id) %></li>
      <li class="list-group-item">Bio: <%= trainer.bio %></li>
      <% avail = trainer.available_on_weekends.to_s %>
      <li class="list-group-item">Available On Weekends? <%= avail == "true"? "Yes" : "No"%></li>
      </ul>
    </div>
    </div>
  <% end %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
<div class="col-4">
<ul class ="list-group">
<li class="list-group-item">Name: <%= @trainer.name %></li>
<li class="list-group-item">Bio: <%= @trainer.bio %></li>
<% avail = @trainer.available_on_weekends.to_s %>
<li class="list-group-item">Available on weekends? <%= avail == "true"? "Yes" : "No" %></li>
</ul>
</div>
<div class="col-8">
<li class="list-group-item"> <%= image_tag "http://static1.squarespace.com/static/52e05773e4b03a73a07d892c/530274dfe4b05f10a2c7bb18/5b20754a0e2e72c2ed6a37ba/1538001231194/?format=1500w" %></li>
</div>
</div>

<br>
<br>

<div class="row">
<div class="col-5">
<ul class ="list-group">
<li class ="list-group-item"><%= "These are the dogs that #{@trainer.name} is training." %></li>
<% @dogs.each do |dog| %>
<li class ="list-group-item"><%=link_to dog.name, dog%></li>
<% end %>
</ul>
</div>
</div>

<br>
<br>

<h3><%= link_to 'Back', trainers_path %></h3>